apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h79fqam9h-nodejs
  janus-idp.io/tekton: h79fqam9h-nodejs
  backstage.io/kubernetes-id: h79fqam9h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h79fqam9h-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
